import type { Metadata } from "next";
import ProfileDialog from "./_components/ProfileDialog";
import LoginDialog from "./_components/LoginDialog";
// import "./globals.css";

export const metadata: Metadata = {
  title: "Vanish",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoginDialog />

        {/* {true ? <ProfileDialog /> : children} */}
      </body>
    </html>
  );
}
